server {
    listen 80;

    # frontend (react build)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # proxy backend
    location /opovo {
       proxy_pass http://backend:5001;

       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
    }
}
